import Product from "../models/Product.js";
import Category from "../models/Category.js";

export const productSeeds = [
  {
    name: "Noir Eclat",
    slug: "noir-eclat",
    description: "A smoky black-amber fragrance with bergamot opening, velvet iris, and a warm cedar finish designed for evening sophistication.",
    brand: "Aurelia",
    categorySlug: "luxury",
    price: 168,
    discountPrice: 149,
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Bergamot", "Iris", "Amber", "Cedar"],
    gender: "unisex",
    volume: "100 ml",
    stock: 42,
    featured: true,
    bestseller: true,
  },
  {
    name: "Santal Soleil",
    slug: "santal-soleil",
    description: "Creamy sandalwood layered with mandarin, tonka, and soft musk for a bright, modern signature scent.",
    brand: "Maison Lumiere",
    categorySlug: "men",
    price: 142,
    discountPrice: 125,
    images: ["https://images.unsplash.com/photo-1557170334-a9632e77c6e0?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Mandarin", "Sandalwood", "Tonka Bean", "Musk"],
    gender: "men",
    volume: "90 ml",
    stock: 28,
    featured: true,
    bestseller: true,
  },
  {
    name: "Rose Obscure",
    slug: "rose-obscure",
    description: "A velvety rose bouquet lifted by pink pepper and cassis, finishing in a deep amber trail.",
    brand: "Atelier 19",
    categorySlug: "women",
    price: 155,
    discountPrice: 139,
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Pink Pepper", "Rose", "Cassis", "Amber"],
    gender: "women",
    volume: "75 ml",
    stock: 34,
    featured: true,
    bestseller: false,
  },
  {
    name: "Cuir dOr",
    slug: "cuir-dor",
    description: "A polished leather composition with saffron, smoke, and cedarwood, crafted for a dramatic luxury statement.",
    brand: "Epoque",
    categorySlug: "luxury",
    price: 210,
    discountPrice: 189,
    images: ["https://images.unsplash.com/photo-1585386959984-a4155223165d?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Saffron", "Leather", "Smoke", "Cedarwood"],
    gender: "unisex",
    volume: "120 ml",
    stock: 16,
    featured: true,
    bestseller: true,
  },
  {
    name: "Iris Nocturne",
    slug: "iris-nocturne",
    description: "Powdered iris and violet wrapped in amber woods, balancing elegance with a soft nocturnal aura.",
    brand: "Aurelia",
    categorySlug: "women",
    price: 186,
    discountPrice: 169,
    images: ["https://images.unsplash.com/photo-1508830524289-0adcbe822b40?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Iris", "Violet", "Amber Woods", "White Musk"],
    gender: "women",
    volume: "100 ml",
    stock: 24,
    featured: false,
    bestseller: false,
  },
  {
    name: "Cedar Veil",
    slug: "cedar-veil",
    description: "Clean cedarwood and aromatic sage softened by citrus and vetiver for a versatile everyday fragrance.",
    brand: "LAtelier",
    categorySlug: "unisex",
    price: 132,
    discountPrice: 119,
    images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Citrus", "Sage", "Cedarwood", "Vetiver"],
    gender: "unisex",
    volume: "75 ml",
    stock: 33,
    featured: false,
    bestseller: true,
  },
  {
    name: "Mint Horizon",
    slug: "mint-horizon",
    description: "Brisk mint and green tea with a soft floral heart and light musk for a refreshing daytime scent.",
    brand: "Verde Isle",
    categorySlug: "unisex",
    price: 98,
    discountPrice: 85,
    images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Mint", "Green Tea", "Lily", "Musk"],
    gender: "unisex",
    volume: "50 ml",
    stock: 60,
    featured: false,
    bestseller: false,
  },
  {
    name: "Amber Atelier",
    slug: "amber-atelier",
    description: "Golden amber fused with labdanum, benzoin and a touch of honey for a warm, gourmand finish.",
    brand: "Atelier 19",
    categorySlug: "luxury",
    price: 194,
    discountPrice: 175,
    images: ["https://images.unsplash.com/photo-1503342452485-86f7f8b32c3a?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Amber", "Labdanum", "Benzoin", "Honey"],
    gender: "women",
    volume: "100 ml",
    stock: 14,
    featured: true,
    bestseller: false,
  },
  {
    name: "Marine Ledger",
    slug: "marine-ledger",
    description: "Aquatic ozone and sea salt paired with driftwood and lavender for a crisp coastal personality.",
    brand: "Nautique",
    categorySlug: "men",
    price: 120,
    discountPrice: 104,
    images: ["https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Ozone", "Sea Salt", "Lavender", "Driftwood"],
    gender: "men",
    volume: "100 ml",
    stock: 40,
    featured: false,
    bestseller: true,
  },
  {
    name: "Vanille Couture",
    slug: "vanille-couture",
    description: "Rich Madagascan vanilla wrapped with tonka, praline, and a whisper of incense for a seductive gourmand.",
    brand: "Couturier",
    categorySlug: "women",
    price: 160,
    discountPrice: 145,
    images: ["https://images.unsplash.com/photo-1595425959632-34b6f89c0b4a?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Vanilla", "Tonka Bean", "Praline", "Incense"],
    gender: "women",
    volume: "90 ml",
    stock: 22,
    featured: true,
    bestseller: true,
  },
  {
    name: "Citrus Passage",
    slug: "citrus-passage",
    description: "Zesty grapefruit and bergamot with a soft floral heart and mineral base, uplifting and clean.",
    brand: "Lumen",
    categorySlug: "unisex",
    price: 88,
    discountPrice: 74,
    images: ["https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Grapefruit", "Bergamot", "Neroli", "Mineral Accord"],
    gender: "unisex",
    volume: "50 ml",
    stock: 75,
    featured: false,
    bestseller: false,
  },
  {
    name: "Spice Meridian",
    slug: "spice-meridian",
    description: "A vibrant spice blend, cardamom, ginger and black pepper over a base of warm woods.",
    brand: "Epoque",
    categorySlug: "men",
    price: 138,
    discountPrice: 124,
    images: ["https://images.unsplash.com/photo-1563170351-be82bc888aa4?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Cardamom", "Ginger", "Black Pepper", "Sandalwood"],
    gender: "men",
    volume: "75 ml",
    stock: 31,
    featured: false,
    bestseller: true,
  },
  {
    name: "Green Bazaar",
    slug: "green-bazaar",
    description: "Herbal basil and fig leaf on a warm patchouli base, earthy, modern, and versatile.",
    brand: "Verde Isle",
    categorySlug: "unisex",
    price: 104,
    discountPrice: 92,
    images: ["https://images.unsplash.com/photo-1505691723518-36a3b10a485b?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Basil", "Fig Leaf", "Patchouli", "Cashmere Wood"],
    gender: "unisex",
    volume: "75 ml",
    stock: 47,
    featured: false,
    bestseller: false,
  },
  {
    name: "Velvet Oud",
    slug: "velvet-oud",
    description: "A luxurious oud fragrance layered with saffron, rose, amber, and smoky woods for a deep and sophisticated signature.",
    brand: "Aurelia",
    categorySlug: "luxury",
    price: 185,
    discountPrice: 159,
    images: ["https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Saffron", "Rose", "Oud", "Amber"],
    gender: "unisex",
    volume: "100 ml",
    stock: 35,
    featured: true,
    bestseller: true,
  },
  {
    name: "Amber Noir",
    slug: "amber-noir",
    description: "A seductive amber composition with bergamot, creamy vanilla, dark woods, and a warm sensual dry-down.",
    brand: "Aurelia",
    categorySlug: "luxury",
    price: 175,
    discountPrice: 149,
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Bergamot", "Amber", "Vanilla", "Dark Woods"],
    gender: "unisex",
    volume: "100 ml",
    stock: 48,
    featured: true,
    bestseller: true,
  },
  {
    name: "Santal Mystique",
    slug: "santal-mystique",
    description: "Creamy sandalwood meets powdery iris, soft musk, and amber in an elegant woody fragrance.",
    brand: "Maison Lumiere",
    categorySlug: "unisex",
    price: 195,
    discountPrice: 169,
    images: ["https://images.unsplash.com/photo-1585386959984-a4155223165d?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Iris", "Sandalwood", "Musk", "Amber"],
    gender: "unisex",
    volume: "100 ml",
    stock: 29,
    featured: true,
    bestseller: false,
  },
  {
    name: "Noir Saffron",
    slug: "noir-saffron",
    description: "A bold oriental fragrance opening with saffron and bergamot before revealing leather, amber, and smoky woods.",
    brand: "Epoque",
    categorySlug: "luxury",
    price: 190,
    discountPrice: 165,
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Saffron", "Bergamot", "Leather", "Amber"],
    gender: "unisex",
    volume: "100 ml",
    stock: 32,
    featured: true,
    bestseller: true,
  },
  {
    name: "Midnight Vanilla",
    slug: "midnight-vanilla",
    description: "Dark vanilla blended with tonka bean, amber, praline, and smoky woods for a warm seductive finish.",
    brand: "Couturier",
    categorySlug: "women",
    price: 170,
    discountPrice: 145,
    images: ["https://images.unsplash.com/photo-1595425959632-34b6f89c0b4a?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Vanilla", "Tonka Bean", "Amber", "Praline"],
    gender: "women",
    volume: "90 ml",
    stock: 44,
    featured: true,
    bestseller: true,
  },
  {
    name: "Imperial Musk",
    slug: "imperial-musk",
    description: "A refined musk fragrance combining powdery iris, warm amber, cedarwood, and soft white musk.",
    brand: "Aurelia",
    categorySlug: "unisex",
    price: 180,
    discountPrice: 155,
    images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Iris", "Musk", "Amber", "Cedarwood"],
    gender: "unisex",
    volume: "100 ml",
    stock: 41,
    featured: false,
    bestseller: true,
  },
  {
    name: "Éclat Rose",
    slug: "eclat-rose",
    description: "A luminous floral fragrance combining bergamot, velvety rose, white musk, and elegant cedarwood.",
    brand: "Atelier 19",
    categorySlug: "women",
    price: 165,
    discountPrice: 139,
    images: ["https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Bergamot", "Rose", "White Musk", "Cedarwood"],
    gender: "women",
    volume: "100 ml",
    stock: 52,
    featured: true,
    bestseller: false,
  },
  {
    name: "Cedar Royale",
    slug: "cedar-royale",
    description: "Fresh citrus and aromatic sage settle into smooth cedarwood and vetiver for a confident everyday fragrance.",
    brand: "LAtelier",
    categorySlug: "men",
    price: 145,
    discountPrice: 128,
    images: ["https://images.unsplash.com/photo-1563170351-be82bc888aa4?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Bergamot", "Sage", "Cedarwood", "Vetiver"],
    gender: "men",
    volume: "100 ml",
    stock: 37,
    featured: false,
    bestseller: true,
  },
  {
    name: "Ocean Noir",
    slug: "ocean-noir",
    description: "A crisp aquatic fragrance with sea salt, bergamot, lavender, and dark driftwood for a modern coastal character.",
    brand: "Nautique",
    categorySlug: "men",
    price: 135,
    discountPrice: 119,
    images: ["https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Sea Salt", "Bergamot", "Lavender", "Driftwood"],
    gender: "men",
    volume: "100 ml",
    stock: 45,
    featured: true,
    bestseller: true,
  },
  {
    name: "Golden Neroli",
    slug: "golden-neroli",
    description: "Bright neroli and orange blossom softened with amber and musk for a radiant and elegant floral scent.",
    brand: "Lumen",
    categorySlug: "women",
    price: 148,
    discountPrice: 129,
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Neroli", "Orange Blossom", "Amber", "Musk"],
    gender: "women",
    volume: "75 ml",
    stock: 38,
    featured: true,
    bestseller: false,
  },
  {
    name: "Black Cardamom",
    slug: "black-cardamom",
    description: "Warm cardamom and black pepper meet leather, incense, and sandalwood in a mysterious spicy composition.",
    brand: "Epoque",
    categorySlug: "men",
    price: 158,
    discountPrice: 139,
    images: ["https://images.unsplash.com/photo-1557170334-a9632e77c6e0?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Cardamom", "Black Pepper", "Leather", "Sandalwood"],
    gender: "men",
    volume: "75 ml",
    stock: 27,
    featured: true,
    bestseller: true,
  },
  {
    name: "Silk Blossom",
    slug: "silk-blossom",
    description: "A delicate floral bouquet of jasmine and peony balanced by pear, musk, and soft sandalwood.",
    brand: "Maison Lumiere",
    categorySlug: "women",
    price: 152,
    discountPrice: 134,
    images: ["https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Pear", "Jasmine", "Peony", "White Musk"],
    gender: "women",
    volume: "75 ml",
    stock: 46,
    featured: true,
    bestseller: false,
  },
  {
    name: "Royal Vetiver",
    slug: "royal-vetiver",
    description: "A refined blend of grapefruit, vetiver, cedar, and earthy patchouli designed for a clean masculine finish.",
    brand: "Verde Isle",
    categorySlug: "men",
    price: 140,
    discountPrice: 122,
    images: ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Grapefruit", "Vetiver", "Cedar", "Patchouli"],
    gender: "men",
    volume: "100 ml",
    stock: 39,
    featured: false,
    bestseller: true,
  },
  {
    name: "Cashmere Amber",
    slug: "cashmere-amber",
    description: "Soft cashmere wood wrapped in golden amber, vanilla, and musk for an elegant warm skin-like finish.",
    brand: "Aurelia",
    categorySlug: "luxury",
    price: 205,
    discountPrice: 179,
    images: ["https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Cashmere Wood", "Amber", "Vanilla", "Musk"],
    gender: "unisex",
    volume: "100 ml",
    stock: 21,
    featured: true,
    bestseller: true,
  },
  {
    name: "White Oud",
    slug: "white-oud",
    description: "A modern interpretation of oud with pear, saffron, white woods, and musk for a clean luxurious character.",
    brand: "Aurelia",
    categorySlug: "luxury",
    price: 198,
    discountPrice: 175,
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Pear", "Saffron", "White Oud", "Musk"],
    gender: "unisex",
    volume: "100 ml",
    stock: 26,
    featured: true,
    bestseller: true,
  }, {
    name: "Oud Majestic",
    slug: "oud-majestic",
    description: "An opulent blend of rare oud wood, smoky incense, and sweet rose absolute, crafted for the ultimate luxury experience.",
    brand: "Atelier 19",
    categorySlug: "luxury",
    price: 245,
    discountPrice: 220,
    images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Oud", "Incense", "Rose Absolute", "Patchouli"],
    gender: "unisex",
    volume: "100 ml",
    stock: 12,
    featured: true,
    bestseller: false,
  },
  {
    name: "Fleur de Soie",
    slug: "fleur-de-soie",
    description: "A delicate and romantic composition featuring silky peony, fresh lychee, and white woods. Perfect for everyday elegance.",
    brand: "Maison Lumiere",
    categorySlug: "women",
    price: 135,
    discountPrice: null,
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Peony", "Lychee", "White Woods", "Freesia"],
    gender: "women",
    volume: "90 ml",
    stock: 45,
    featured: false,
    bestseller: true,
  },
  {
    name: "Aqua Vento",
    slug: "aqua-vento",
    description: "A rush of coastal wind featuring icy marine notes, crisp bergamot, and a grounding base of oakmoss.",
    brand: "Nautique",
    categorySlug: "men",
    price: 115,
    discountPrice: 95,
    images: ["https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Marine Notes", "Bergamot", "Oakmoss", "Ambroxan"],
    gender: "men",
    volume: "100 ml",
    stock: 55,
    featured: false,
    bestseller: true,
  },
  {
    name: "Vetiver Blanc",
    slug: "vetiver-blanc",
    description: "A minimalist masterpiece blending clean vetiver root, white grapefruit, and a hint of white pepper.",
    brand: "Lumen",
    categorySlug: "unisex",
    price: 95,
    discountPrice: null,
    images: ["https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Vetiver", "White Grapefruit", "White Pepper", "Musk"],
    gender: "unisex",
    volume: "50 ml",
    stock: 30,
    featured: true,
    bestseller: false,
  },
  {
    name: "Neroli d'Or",
    slug: "neroli-dor",
    description: "Sun-drenched neroli blossoms layered with bitter orange and honey, capturing the essence of golden hour.",
    brand: "Aurelia",
    categorySlug: "luxury",
    price: 185,
    discountPrice: 165,
    images: ["https://images.unsplash.com/photo-1585386959984-a4155223165d?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Neroli", "Bitter Orange", "Honey", "Amber"],
    gender: "women",
    volume: "75 ml",
    stock: 18,
    featured: true,
    bestseller: true,
  },
  {
    name: "Noir Intense",
    slug: "noir-intense",
    description: "A bold, charismatic fragrance combining roasted coffee, dark chocolate, and spicy cardamom on a woodsy base.",
    brand: "Epoque",
    categorySlug: "men",
    price: 150,
    discountPrice: 135,
    images: ["https://images.unsplash.com/photo-1557170334-a9632e77c6e0?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Coffee", "Dark Chocolate", "Cardamom", "Cedar"],
    gender: "men",
    volume: "100 ml",
    stock: 25,
    featured: true,
    bestseller: false,
  },
  {
    name: "Jasmin Rouge",
    slug: "jasmin-rouge",
    description: "An intoxicating blend of pure jasmine absolute, ylang-ylang, and a touch of warm vanilla.",
    brand: "Atelier 19",
    categorySlug: "women",
    price: 145,
    discountPrice: 125,
    images: ["https://images.unsplash.com/photo-1508830524289-0adcbe822b40?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Jasmine Absolute", "Ylang-Ylang", "Vanilla", "Sandalwood"],
    gender: "women",
    volume: "50 ml",
    stock: 32,
    featured: false,
    bestseller: true,
  },
  {
    name: "Cedar & Fig",
    slug: "cedar-fig",
    description: "The sweetness of ripe figs beautifully contrasted with dry, aromatic atlas cedarwood and fresh green leaves.",
    brand: "Verde Isle",
    categorySlug: "unisex",
    price: 110,
    discountPrice: null,
    images: ["https://images.unsplash.com/photo-1505691723518-36a3b10a485b?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Fig", "Green Leaves", "Atlas Cedar", "Musk"],
    gender: "unisex",
    volume: "100 ml",
    stock: 40,
    featured: false,
    bestseller: false,
  },
  {
    name: "Patchouli Nuit",
    slug: "patchouli-nuit",
    description: "A dark, enigmatic interpretation of patchouli, enriched with leather, plum, and smoky vetiver.",
    brand: "Couturier",
    categorySlug: "luxury",
    price: 215,
    discountPrice: 190,
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Patchouli", "Leather", "Plum", "Smoky Vetiver"],
    gender: "unisex",
    volume: "120 ml",
    stock: 10,
    featured: true,
    bestseller: false,
  },
  {
    name: "Citrus Bloom",
    slug: "citrus-bloom",
    description: "A joyful explosion of Sicilian lemon, mandarin, and blooming orange blossom. Bright, bubbly, and uplifting.",
    brand: "LAtelier",
    categorySlug: "women",
    price: 85,
    discountPrice: null,
    images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Sicilian Lemon", "Mandarin", "Orange Blossom", "White Musk"],
    gender: "women",
    volume: "90 ml",
    stock: 65,
    featured: false,
    bestseller: true,
  },

];

export const seedProducts = async () => {
  const categories = await Category.find({
    slug: {
      $in: [...new Set(productSeeds.map((product) => product.categorySlug))],
    },
  });

  const categoryMap = new Map(categories.map((category) => [category.slug, category._id]));
  const products = [];

  for (const product of productSeeds) {
    const category = categoryMap.get(product.categorySlug);

    if (!category) {
      throw new Error(`Missing category for product seed: ${product.categorySlug}`);
    }

    const payload = {
      name: product.name,
      slug: product.slug,
      description: product.description,
      brand: product.brand,
      category,
      price: product.price,
      discountPrice: product.discountPrice,
      images: product.images,
      fragranceNotes: product.fragranceNotes,
      gender: product.gender,
      volume: product.volume,
      stock: product.stock,
      featured: product.featured,
      bestseller: product.bestseller,
    };

    const document = await Product.findOneAndUpdate(
      { slug: product.slug },
      { $set: payload },
      { new: true, upsert: true, runValidators: true }
    );

    products.push(document);
  }

  console.log("Products seeded");
  return products;
};
