import Product from "../models/Product.js";
import Category from "../models/Category.js";

export const productSeeds = [
  {
    name: "Noir Eclat",
    slug: "noir-eclat",
    description: "A smoky black-amber fragrance with bergamot opening, velvet iris, and a warm cedar finish designed for evening sophistication.",
    brand: "Aurelia",
    categorySlug: "luxury",
    price: 168,
    discountPrice: 149,
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Bergamot", "Iris", "Amber", "Cedar"],
    gender: "unisex",
    volume: "100 ml",
    stock: 42,
    featured: true,
    bestseller: true,
  },
  {
    name: "Santal Soleil",
    slug: "santal-soleil",
    description: "Creamy sandalwood layered with mandarin, tonka, and soft musk for a bright, modern signature scent.",
    brand: "Maison Lumiere",
    categorySlug: "men",
    price: 142,
    discountPrice: 125,
    images: ["https://images.unsplash.com/photo-1557170334-a9632e77c6e0?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Mandarin", "Sandalwood", "Tonka Bean", "Musk"],
    gender: "men",
    volume: "90 ml",
    stock: 28,
    featured: true,
    bestseller: true,
  },
  {
    name: "Rose Obscure",
    slug: "rose-obscure",
    description: "A velvety rose bouquet lifted by pink pepper and cassis, finishing in a deep amber trail.",
    brand: "Atelier 19",
    categorySlug: "women",
    price: 155,
    discountPrice: 139,
    images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Pink Pepper", "Rose", "Cassis", "Amber"],
    gender: "women",
    volume: "75 ml",
    stock: 34,
    featured: true,
    bestseller: false,
  },
  {
    name: "Cuir dOr",
    slug: "cuir-dor",
    description: "A polished leather composition with saffron, smoke, and cedarwood, crafted for a dramatic luxury statement.",
    brand: "Epoque",
    categorySlug: "luxury",
    price: 210,
    discountPrice: 189,
    images: ["https://images.unsplash.com/photo-1585386959984-a4155223165d?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Saffron", "Leather", "Smoke", "Cedarwood"],
    gender: "unisex",
    volume: "120 ml",
    stock: 16,
    featured: true,
    bestseller: true,
  },
  {
    name: "Iris Nocturne",
    slug: "iris-nocturne",
    description: "Powdered iris and violet wrapped in amber woods, balancing elegance with a soft nocturnal aura.",
    brand: "Aurelia",
    categorySlug: "women",
    price: 186,
    discountPrice: 169,
    images: ["https://images.unsplash.com/photo-1508830524289-0adcbe822b40?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Iris", "Violet", "Amber Woods", "White Musk"],
    gender: "women",
    volume: "100 ml",
    stock: 24,
    featured: false,
    bestseller: false,
  },
  {
    name: "Cedar Veil",
    slug: "cedar-veil",
    description: "Clean cedarwood and aromatic sage softened by citrus and vetiver for a versatile everyday fragrance.",
    brand: "LAtelier",
    categorySlug: "unisex",
    price: 132,
    discountPrice: 119,
    images: ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Citrus", "Sage", "Cedarwood", "Vetiver"],
    gender: "unisex",
    volume: "75 ml",
    stock: 33,
    featured: false,
    bestseller: true,
  },
  {
    name: "Mint Horizon",
    slug: "mint-horizon",
    description: "Brisk mint and green tea with a soft floral heart and light musk for a refreshing daytime scent.",
    brand: "Verde Isle",
    categorySlug: "unisex",
    price: 98,
    discountPrice: 85,
    images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Mint", "Green Tea", "Lily", "Musk"],
    gender: "unisex",
    volume: "50 ml",
    stock: 60,
    featured: false,
    bestseller: false,
  },
  {
    name: "Amber Atelier",
    slug: "amber-atelier",
    description: "Golden amber fused with labdanum, benzoin and a touch of honey for a warm, gourmand finish.",
    brand: "Atelier 19",
    categorySlug: "luxury",
    price: 194,
    discountPrice: 175,
    images: ["https://images.unsplash.com/photo-1503342452485-86f7f8b32c3a?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Amber", "Labdanum", "Benzoin", "Honey"],
    gender: "women",
    volume: "100 ml",
    stock: 14,
    featured: true,
    bestseller: false,
  },
  {
    name: "Marine Ledger",
    slug: "marine-ledger",
    description: "Aquatic ozone and sea salt paired with driftwood and lavender for a crisp coastal personality.",
    brand: "Nautique",
    categorySlug: "men",
    price: 120,
    discountPrice: 104,
    images: ["https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Ozone", "Sea Salt", "Lavender", "Driftwood"],
    gender: "men",
    volume: "100 ml",
    stock: 40,
    featured: false,
    bestseller: true,
  },
  {
    name: "Vanille Couture",
    slug: "vanille-couture",
    description: "Rich Madagascan vanilla wrapped with tonka, praline, and a whisper of incense for a seductive gourmand.",
    brand: "Couturier",
    categorySlug: "women",
    price: 160,
    discountPrice: 145,
    images: ["https://images.unsplash.com/photo-1595425959632-34b6f89c0b4a?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Vanilla", "Tonka Bean", "Praline", "Incense"],
    gender: "women",
    volume: "90 ml",
    stock: 22,
    featured: true,
    bestseller: true,
  },
  {
    name: "Citrus Passage",
    slug: "citrus-passage",
    description: "Zesty grapefruit and bergamot with a soft floral heart and mineral base, uplifting and clean.",
    brand: "Lumen",
    categorySlug: "unisex",
    price: 88,
    discountPrice: 74,
    images: ["https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Grapefruit", "Bergamot", "Neroli", "Mineral Accord"],
    gender: "unisex",
    volume: "50 ml",
    stock: 75,
    featured: false,
    bestseller: false,
  },
  {
    name: "Spice Meridian",
    slug: "spice-meridian",
    description: "A vibrant spice blend, cardamom, ginger and black pepper over a base of warm woods.",
    brand: "Epoque",
    categorySlug: "men",
    price: 138,
    discountPrice: 124,
    images: ["https://images.unsplash.com/photo-1563170351-be82bc888aa4?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Cardamom", "Ginger", "Black Pepper", "Sandalwood"],
    gender: "men",
    volume: "75 ml",
    stock: 31,
    featured: false,
    bestseller: true,
  },
  {
    name: "Green Bazaar",
    slug: "green-bazaar",
    description: "Herbal basil and fig leaf on a warm patchouli base, earthy, modern, and versatile.",
    brand: "Verde Isle",
    categorySlug: "unisex",
    price: 104,
    discountPrice: 92,
    images: ["https://images.unsplash.com/photo-1505691723518-36a3b10a485b?auto=format&fit=crop&w=1200&q=80"],
    fragranceNotes: ["Basil", "Fig Leaf", "Patchouli", "Cashmere Wood"],
    gender: "unisex",
    volume: "75 ml",
    stock: 47,
    featured: false,
    bestseller: false,
  },
];

export const seedProducts = async () => {
  const categories = await Category.find({
    slug: {
      $in: [...new Set(productSeeds.map((product) => product.categorySlug))],
    },
  });

  const categoryMap = new Map(categories.map((category) => [category.slug, category._id]));
  const products = [];

  for (const product of productSeeds) {
    const category = categoryMap.get(product.categorySlug);

    if (!category) {
      throw new Error(`Missing category for product seed: ${product.categorySlug}`);
    }

    const payload = {
      name: product.name,
      slug: product.slug,
      description: product.description,
      brand: product.brand,
      category,
      price: product.price,
      discountPrice: product.discountPrice,
      images: product.images,
      fragranceNotes: product.fragranceNotes,
      gender: product.gender,
      volume: product.volume,
      stock: product.stock,
      featured: product.featured,
      bestseller: product.bestseller,
    };

    const document = await Product.findOneAndUpdate(
      { slug: product.slug },
      { $set: payload },
      { new: true, upsert: true, runValidators: true }
    );

    products.push(document);
  }

  console.log("Products seeded");
  return products;
};
